version: '3.0'
services:
  postgres:
    image: postgres:14.1-alpine
    volumes:
      - ./postgres/mattermost.sql:/docker-entrypoint-initdb.d/00-mattermost.sql
      - ./postgres/setup-synapse.sql:/docker-entrypoint-initdb.d/01-setup-synapse.sql
      - ./postgres/synapse.sql:/docker-entrypoint-initdb.d/02-synapse.sql
      - ./postgres/setup-bridge.sql:/docker-entrypoint-initdb.d/03-setup-bridge.sql
    environment:
      # We create synapse database in 01-setup.sql
      - POSTGRES_USER=mattermost
      - POSTGRES_DB=mattermost
      - POSTGRES_PASSWORD=hunter2
    ports:
      - '5432:5432'

  mattermost:
    build: mattermost
    ports:
      - '8065:8065'

  synapse:
    build: synapse
    ports:
      - '8008:8008'
    volumes:
      - ./synapse/registration.yaml:/etc/synapse/registration.yaml

  appservice:
    build: appservice
    ports:
      - '8022:22'
