type: 'object'
properties:
  appservice:
    type: object
    required: true
    properties:
      port:
        type: number
        required: true
        minimum: 0
        maximum: 65535
      hostname:
        type: string
        required: true
      schema:
        type: string
        enum: ['https', 'http']
        required: true
  mattermost_url:
    type: string
    format: uri
    required: true
  admin_port:
    type: number
    minimum: 0
    maximum: 65535
  mattermost_bot_userid:
    type: 'string'
    required: true
  mattermost_bot_access_token:
    type: 'string'
    required: true
  forbid_bridge_failure:
    type: boolean
    default: false
  mappings:
    type: 'array'
    required: true
    items:
      type: 'object'
      properties:
        mattermost:
          type: 'string'
          pattern: '^[a-z0-9]{26}$'
          required: true
        matrix:
          type: 'string'
          pattern: '^!.*:.*$'
          required: true
  matrix_localpart_prefix:
    type: 'string'
    default: 'mm_'
  matrix_display_name_template:
    type: 'string'
    default: '[DISPLAY]'
  mattermost_username_template:
    type: 'string'
    default: '[DISPLAY]'
  matrix_bot:
    type: object
    properties:
      username:
        type: string
        required: true
      display_name:
        type: string

  logging:
    type: 'string'
    enum: ['trace', 'debug', 'info', 'warn', 'error', 'silent']
  homeserver:
    type: 'object'
    properties:
      server_name:
        type: string
        required: true
      url:
        type: string
        pattern: '^https?://'
        required: true
  database:
    type: 'object'
    properties:
      type:
        type: string
        required: true
      host:
        type: string
        required: true
      port:
        type: number
      username:
        type: string
        required: true
      password:
        type: string
      database:
        type: string
        required: true
  ignored_mattermost_users:
    type: 'array'
    items:
      type: 'string'
  ignored_matrix_users:
    type: 'array'
    items:
      type: 'string'
  mattermost_email_template:
    type: 'string'
    required: true
